server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  datasource:
    url: jdbc:h2:mem:test-h2-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 40
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml

