server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coin?autoReconnect=true
    username: root
    password: rootRoot!23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
